### DISCUSSION TITLE
Merge metadata or separate events?

### DISCUSSION THREAD

**Discussion by asimpleidea** [CloudNativeSDWAN/cnwan-reader#23] [General]
This is more of a discussion for the future.
We are currently sending endpoints with metadata of the parent service.

Although, since we have metadata on every service registry, should we provide a way to merge metadata?

For example, service has metadata:

```yaml
traffic-profile: this
hash-commit: that
```

and metadata has:

```yaml
key1: val1
key2: val2
```

Of course, we may have potential overwrite but to avoid it we could even separa events for service AND endpoints, i.e.:

```yaml
event: new
type: service
service: 
  name: this
  ...
```

```yaml
event: update
type: endpoint
endpoint: 
  name: that
  serviceName: this
  ...
```

This being said, this second thought (providing a `type` for events) may prove to be actually more scalable for future implementations in case we may have multiple objects triggering events.
